### ISSUE TITLE
SEO-friendly URLs within the sitemap.xml files/pages?

### ISSUE THREAD

**Issue by Concept211** [tas2580/sitemap#1]
I currently have your other mod for generating SEO-friendly URLs for the forums and topics. Is there any way that this sitemap mod could be changed to use those URLs instead? It would make most sense instead of telling the search engines to index the standard URLs.

thanks!

**Comment by tas2580** [comment]
Which SEO extension do you use?

**Comment by Concept211** [comment]
I use your extension: https://github.com/tas2580/seourls

**Comment by tas2580** [comment]
There is already a XML sitemap included

"You can access the XML sitemap under {YOUR_BOARD_URL}/seositemap.xml"

**Comment by Concept211** [comment]
Ah! Wasn't even aware of it.  Thanks!

**Comment by LuigiMdg** [comment]
Hi..
I've the same problem.. I've installed your SEO Urls extension and the XML Sitemap extension, but if I go to {MY_BOARD_URL}/seositemap.xml this not work..!

**Comment by tas2580** [comment]
Try {MY_BOARD_URL}/sitemap.xml or {MY_BOARD_URL}/app.php/sitemap.xml
